### ISSUE TITLE
Use cases for clickhouse-flamegraph tool

### ISSUE THREAD

**Issue by Jefferson111** [Slach/clickhouse-flamegraph#18]
Hi, is it possible to provide some use cases for the clickhouse-flamegraph tool. I still don't know how to use even with the usage in readme. 😅 As a user, what am I suppose to put for command and arguments, what do they even refer to? Where and when is the flamegraph svg generated, will a flamegraph be automatically generated whenever a client query? Or do I need to use the clickhouse-flamegraph tool to perform the query? It would be great if there could be a use case to follow through that helps the user to generate one flamegraph. Thank you! 😆

**Comment by Slach** [comment]
Short answer:
Just read `clickhouse-flamegraph --help` luke and feel the power of flamegraph ;)

Long answer:
Only one use-case for clickhouse-flamegraph which I see currently 
When you try to find CPU / Memory bottleneck in your SQL queries and you can understand clickhouse internals to right interpreted results

> As a user, what am I supposed to put for command and arguments, what do they even refer to?
first of all, you should change your `clickhouse-server` settings, via `/etc/clickhouse-server/users.d/profiling.xml` as described in README.md, or you can try to add `SETTINGS query_profiler_real_time_period_ns=10000000, log_queries=1` to your SQL queries, which you try to find a bottleneck
 
most of parameters just describe how to `clickhouse-flamegraph` can connect to `clickhouse-server`
and which date range it should use to grab stack traces from `system.trace_log` and SQL queries from `system.query_log`

> Where and when is the flamegraph svg generated, will a flamegraph be automatically generated whenever a client query?

stack traces as an array of "stack address" captured inside clickhouse-server automatically for all running queries after you change server settings as described in https://github.com/Slach/clickhouse-flamegraph/blob/master/docker/clickhouse/profiling.xml

or you can use `SETTINGS` section inside your SQL queries for try to find a bottleneck selectively 

SVG files generated in directory get from `--output-dir` CLI parameter 
SVG files it's a just representation of selected rows from system.trace_log with transform over clickhouse SQL function `addressToSymbol`

>  Or do I need to use the clickhouse-flamegraph tool to perform the query?
no, currently clickhouse-flamegraph doesn't run user queries, you should run your queries in separate clickhouse-client, but I think about add this functionality to my roadmap

**Comment by Jefferson111** [comment]
> > Hi, is it possible to provide some use cases for the clickhouse-flamegraph tool. I still don't know how to use even with the usage in readme.
> 
> Short answer:
> Just read `clickhouse-flamegraph --help` luke and feel the power of flamegraph ;)
> 
> Long answer:
> Only one use-case for clickhouse-flamegraph which I see currently
> When you try to find CPU / Memory bottleneck in your SQL queries and you can understand clickhouse internals to right interprets results
> 
> > As a user, what am I supposed to put for command and arguments, what do they even refer to?
> 
> first of all, you should change your `clickhouse-server` settings, via `/etc/clickhouse-server/users.d/profiling.xml` as described in README.md, or you can try to add `SETTINGS query_profiler_real_time_period_ns=10000000, log_queries=1` to your SQL queries, which you try to find a bottleneck
> 
> most of parameters just describe how to `clickhouse-flamegraph` can connect to `clickhouse-server`
> and which date range it should use to grab stack traces from `system.trace_log` and SQL queries from `system.query_log`
> 
> > Where and when is the flamegraph svg generated, will a flamegraph be automatically generated whenever a client query?
> 
> stack traces as an array of "stack address" captured and stored to `system.trace_log` table inside clickhouse-server automatically for all running queries after you change server settings as described in https://github.com/Slach/clickhouse-flamegraph/blob/master/docker/clickhouse/profiling.xml
> 
> or you can use `SETTINGS` section inside your SQL queries for try to find a bottleneck selectively
> 
> SVG files generated in directory get from `--output-dir` CLI parameter
> SVG files it's a just representation of selected rows from system.trace_log with transform over clickhouse SQL function `addressToSymbol`
> 
> > Or do I need to use the clickhouse-flamegraph tool to perform the query?
> 
> no, currently clickhouse-flamegraph doesn't run user queries, you should run your queries in separate clickhouse-client, but I think about add this functionality to my roadmap

Thank you, your answer is very informative and helpful!! What I really struggled was with the usage as it was so simple 😆 which made it really hard to get. 

I wasn't sure whether command and global options were referring to the same things, and I thought there were an entire set of commands on top of that; unbeknownst to the users, which was the source of my confusion. 😂😂
